export const projects = [
  {
    title: 'Easy Bank Landing Page',
    description: "This is a responsive landing page challange from fron-end mentore, I build this website using Html and Sass",
    image: '/images/easybank.jpg',
    tags: ['Html', 'Sass'],
    source: 'https://github.com/hrithikrawal/EASYBANK-landing-page',
    visit: 'https://web-easybank.netlify.app/',
    id: 0,
  },
  {
    title: 'E-commerce',
    description: "Using React, Django I build a Full Stack simple e-commerce app that allows users to login and buy & review the products.",
      image: '/images/Project1.png',
      tags: ['React', 'Django', 'Python'],
    source: 'https://github.com/hrithikrawal/shopzila-live',
    visit: 'https://shopzila.herokuapp.com/',
    id: 1,
  },
  {
    title: 'Food Recipe',
    description:"Using Javascript and TheMealDb api I build a food recipe app and the tutorial is also available.",
    image: '/images/Project2.png',
    tags: ['Html', 'Css', 'JavaScript'],
    source: 'https://github.com/hrithikrawal/food-web',
    visit: 'https://hrithikrawal.github.io/food-web/',
    id: 2,
  },
  {
    title: 'E-commerce',
    description: "This is a simple e-commerce app build with Django. It has basic features like view products7, add to cart and checkout.",
      image: '/images/Project3.png',
      tags: ['Javascript', 'Bootstrap', 'Django', 'Python'],
    source: 'https://github.com/hrithikrawal/shop-4-u',
    visit: 'https://shop-4-u.herokuapp.com/',
    id: 3,
  },
  {
    title: 'Landing Page',
    description: "This is a simple onepage website, build with Html and Sass. It also looks well in small screen devices.",
      image: '/images/Project4.png',
      tags: ['Html', 'Sass'],
    source: 'https://github.com/hrithikrawal/UI-Responsive-Website',
    visit: 'https://leica-cam.netlify.app/',
    id: 4,
  },

];